version: "3"
services:
    api:
      build: .
      ports:
        - 8000:8000
      volumes:
        - ./:/usr/src/app
      environment:
        # We can reference postgres service name, so database hostnaem will link to that
        - DATABASE_HOSTNAME=postgres
        - DATABASE_PORT=5432
        - DATABASE_PASSWORD=password123
        - DATABASE_NAME=fastapi
        - DATABASE_USERNAME=postgres
        - SECRET_KEY=ba25af314d040d2464e25d7265b7bb64448c32bfb7700eb57462fefe90e692b2
        - ALGORITHM=HS256
        - ACCESS_TOKEN_EXPIRE_MINUTES=30
      # Waits for postgres container to start before starting api service
      command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      depends_on:
        - postgres
    
    postgres:
      image: postgres
      environment:
        - POSTGRES_PASSWORD = password123
        - POSTGRES_DB = fastapi
      # Volumes allow us to save data from a container onto our local machine, so if we kill a container, when it comes up it can pull from 
      # this volume
      volumes:
        - postgres-db:/var/lib/postgresql/data
  
volumes:
  postgres-db:
