name: Build and Deploy Code

on: [push, pull_request]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git Repository ${{ github.repository }}
        uses: action/checkout@v2
      - name: Echo to user
        run: echo "Hello Tommy"
      
      